### ISSUE TITLE
`game_of_life`后续建议

### ISSUE THREAD

**Issue by chenkan** [lgn21st/game_of_life#1]
以实现`小游戏`这种形式学习ruby很有意思；
细胞自动机这个游戏不如考虑将其完整做出来，并补充一些其它基础知识；
后续`game_if_life`这个repo可以作为ruby社区的一门新人入门教程

**Comment by lgn21st** [comment]
@chenkan 我觉得你的建议很好，我们这个细胞自动机本来就是一套（三集）针对新手的入门视频教程的配套代码，对后续应该如何扩展完善，你有什么建议呢？

### 视频教程
1. [Two Daniel Pair Live Show session 1](http://railscasts-china.com/episodes/two-daniel-pair-live-show)
2. [Two Daniel Pair Live Show session 2](http://railscasts-china.com/episodes/two-daniel-pair-live-show2)
3. [Two Daniel Pair Live Show session 3](http://railscasts-china.com/episodes/two-daniel-pair-live-show3)

**Comment by chenkan** [comment]
@lgn21st 我是在`RailsCast`看到这个视频后再来Github看源码的：-）

一些改进意见：
1. 视频节奏稍慢，我是顶着1.3倍速率看的
2. 在一些有`新`概念出现的地方，可以在屏幕上打出`Keyword`提示大家注意，并简单介绍。例如：第一次出现rspec的时候，可以说这是一个BDD框架，在Ruby社区目前是主流测试框架之类的，屏幕上打出`rspec`及`BDD`字眼。点到即止，提示观众去自学
3. 把`细胞自动机`做到可以显示出来并运行的阶段，初学者看了以后应该会更有感觉！

**Comment by lgn21st** [comment]
@chenkan 谢谢你的建议。
1. 关于速度，这个视频不是一个事先就充分准备妥当的教学演示视频，而是两个人真实开发时候的实际速度。
2. 第二期第三期发布视频的时候，我已经添加了相应的字幕信息，但是960x600的范围内不适合大量文字信息，我们可以在每个screencast的介绍页面中增加这部分内容。
3. 细胞自动机的后续完善工作可以留给看视频的人自行完成，因为我们的目标是演示 pair programming 以及TDD，这部分是我们的重点。
